### ISSUE TITLE
Can not build on mac

### ISSUE THREAD

**Issue by huangboju** [jordansinger/SwiftUI-Kit#43]
* Xcode 12.0.1
* macOS 10.15.7 

![image](https://user-images.githubusercontent.com/14818224/96744812-01ec1b80-13f8-11eb-859d-d8a3abac8689.png)

**Comment by MartinP7r** [comment]
I didn't verify this, but the iOS 14 APIs might not be available on mac if you're trying to build this on a macOS version below Big Sur.  
Meaning, if you're trying to build this on Catalina, it won't work because the equivalent APIs to translate those SwiftUI elements to are not there yet.  
The readme.md also states that it's built for Big Sur.

**Comment by huangboju** [comment]
I have upgraded the system, It‘s working
